#!/bin/sh
set -x

if [ -n "$1" ]; then
    ip tuntap add dev $1 mode tap user `whoami`
    ip addr add 192.168.1.1/24 dev $1
    ip link set $1 up
    sysctl -w net.ipv4.ip_forward=1
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi
